version: '3'
services:
	web:
		image: treeptik/devoxx2018
		restart: unless-stopped
		labels:
		- "traefik.http.routers.master.rule=Host(`master.localhost`)"
		- "traefik.http.routers.master.entrypoints=http"
		- "traefik.http.services.master.loadbalancer.server.port=8080"

	database:
		image: postgres:10
		volumes:
		- "/mnt/btrfs/pg-master:/var/lib/postgresql/data"
		environment:
		- POSTGRES_PASSWORD=mysecretpassword
		restart: unless-stopped
		labels:
		- "traefik.enable=false"
		
networks:
	default:
		external:
			name: skynet